version: '3'

services:
  postgresql:
    image: postgres:12.1-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_USER=documize
      - POSTGRES_PASSWORD=documize
      - POSTGRES_DB=documize
    networks:
      - backend

  documize:
    depends_on: 
     - postgresql
    build:
      context: ./documize-image
    ports:
      - 8080:8080
    networks:
      - backend

  #nginx

volumes:
  postgresql-data: {}
  documize-data: {}

networks:
  backend: {}